# Generated by Django 4.2.3 on 2023-08-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_advertisement_image_advertisement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
    ]
