# Generated by Django 4.2.3 on 2023-08-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0006_advertisement_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
